### ISSUE TITLE
Update Tink SHA-1 value with the latest maven snapshot

### ISSUE THREAD

**Issue by serranos** [thaidn/tink-examples#2]
Hi.

I was playing with the timestamper example, it seems a new Tink artifact was released and the current build process is broken. I tried to open a PR but it seems they aren't opened. The diff is the following:

```
diff --git a/WORKSPACE b/WORKSPACE
index ac1b6cb..c97cdff 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -8,7 +8,7 @@ maven_server(
 maven_jar(
     name = "com_google_crypto_tink_tink",
     artifact = "com.google.crypto.tink:tink:1.1.0-SNAPSHOT",
-    sha1 = "8bc3c32a50b259541d535d7bd494b70b142c753d",
+    sha1 = "b8fd5f8958ea723264803e93910e12e0e1e391b6",
     server = "maven_central_snapshot",
 )
```

Reference: https://oss.sonatype.org/content/repositories/snapshots/com/google/crypto/tink/tink/1.1.0-SNAPSHOT/tink-1.1.0-20180228.000645-15.jar.sha1

Thanks for the work.

**Comment by thaidn** [comment]
Thanks for reporting. This should be fixed now.
